import type { NextPage } from "next";
import Head from "next/head";
import Sidebar from "../components/Sidebar";
import "tailwindcss/tailwind.css";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>WhatChat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Sidebar />
      </main>

      <footer className=""></footer>
    </div>
  );
};

export default Home;
